// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvj4USjiMAg8RcZvRWYSvTwEi_B9ax2fc',
    appId: '1:900967099518:web:639c5d49853241d5f07c2f',
    messagingSenderId: '900967099518',
    projectId: 'book-app-aa113',
    authDomain: 'book-app-aa113.firebaseapp.com',
    storageBucket: 'book-app-aa113.appspot.com',
    measurementId: 'G-0SZJC9LX56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcnJghRLQPrIQtJFOyEj6gkIONYAHIm2c',
    appId: '1:900967099518:android:0492cc49dddcdd2bf07c2f',
    messagingSenderId: '900967099518',
    projectId: 'book-app-aa113',
    storageBucket: 'book-app-aa113.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR-gizELo9fRCBuJxsf4qh92TDRPHJ6no',
    appId: '1:900967099518:ios:39330dd62ddd6ce4f07c2f',
    messagingSenderId: '900967099518',
    projectId: 'book-app-aa113',
    storageBucket: 'book-app-aa113.appspot.com',
    iosBundleId: 'com.example.booklyApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR-gizELo9fRCBuJxsf4qh92TDRPHJ6no',
    appId: '1:900967099518:ios:39330dd62ddd6ce4f07c2f',
    messagingSenderId: '900967099518',
    projectId: 'book-app-aa113',
    storageBucket: 'book-app-aa113.appspot.com',
    iosBundleId: 'com.example.booklyApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvj4USjiMAg8RcZvRWYSvTwEi_B9ax2fc',
    appId: '1:900967099518:web:0dc2c71944266a60f07c2f',
    messagingSenderId: '900967099518',
    projectId: 'book-app-aa113',
    authDomain: 'book-app-aa113.firebaseapp.com',
    storageBucket: 'book-app-aa113.appspot.com',
    measurementId: 'G-8RRJP2J73P',
  );
}
